# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d03835a3e1bb16866e63ecf9f128350630d6fb80aa816aa320ef429c5c54fa399b6db279c2fc55d2923a394d65457096166cc72182558408ef57d75d35ab9f6a

test:
  secret_key_base: 0dc92a3184ffbec9d2f74a55db45514d24f2a93ba38843d9a484ee0b135cc1879af1ea2a0968e156131993859bf8b21f0640c7d1e6a1e532a915120aead46e12

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
